### ISSUE TITLE
on initial screen, user should be able to select if they want to search 'early voting locations' or 'election day voting locations'

### ISSUE THREAD

**Issue by Noah-T** [codeforboston/cambridge_voting_locations#28]

**Comment by cranti** [comment]
I chatted about this with Lee and Josh -- it might make sense to have two options for the user from the initial screen:

**1) Where can I vote today?** 
- This should be available on days when polling places are open
- If it is an early voting day, go straight to the map and display all of the early voting locations (plus hours)
  - Possible enhancement: prompt a user to enter a starting address (or use the current location), to highlight the closest polling place
  - Another possible enhancement: only display voting locations that are currently open
- If it is election day, ask the user for their home address

**2) Show all my polling locations**
- Ask the user for their home address, and display their polling place

**Comment by carpeliam** [comment]
@thecristen do you think we've satisfied this issue?

**Comment by thecristen** [comment]
Yes, I'd say this is done. :tada:
