### ISSUE TITLE
Move to HTTPS by default to fix "Find Current Location" in Chrome 53+

### ISSUE THREAD

**Issue by thadk** [codeforboston/cambridge_voting_locations#46]
The latest version of chrome does not support location tracking without using secure HTTPS for user safety.

We should consider setting up a free reverse proxy with https://www.cloudflare.com/ and moving the domain. @WheresHJ, can you please comment on where the DNS is hosted for this for our memory.

**Comment by thadk** [comment]
If we ( @WheresHJ  ) switch our domain to this DNS below, it will start using Cloudflare and gain SSL. I can change the email of the cloudflare account (and password) if you tell me which one to use.
![image](https://cloud.githubusercontent.com/assets/283343/19294315/62252b0e-8ff9-11e6-8010-da661b65b333.png)

**Comment by carpeliam** [comment]
Does https://letsencrypt.org work for us?

**Comment by thadk** [comment]
I use LetsEncrypt on my personal server. It is awesome. I have a cronjob that renews it every 90 days as required and updates nginx. I don't think that is something we want in this case though. 
Cloudflare is a top-100 standard service that (amongst other things) takes care of details and adds encryption to github sites as an overlay. It should solve our issue for our essentially client side app.

**Comment by thadk** [comment]
Moving from github pages to heroku is another viable solution which would also give us HTTPS at some minor technical cost.

**Comment by WheresHJ** [comment]
@beechnut and I just changed these nameservers. Let us know if this was successful @thadk .

**Comment by thadk** [comment]
Ahh nonstop class today forgot it was Tuesday and double booked. I'll keep an eye on it and do what I can from the Cloudflare. Right now it is still redirecting.

**Comment by carpeliam** [comment]
@thadk your DNS might be cached - I tried it just now, and instead of getting an untrusted cert issue (which I seem to remember getting before), I got "This site can’t provide a secure connection - votecambridge.com sent an invalid response."

**Comment by thadk** [comment]
![image](https://cloud.githubusercontent.com/assets/283343/19735585/36393bc0-9b7a-11e6-8726-876849508e3b.png)
 I just told Cloudflare to rescan, and it says we should try again in a couple hours.

**Comment by thadk** [comment]
Hurray:
![image](https://cloud.githubusercontent.com/assets/283343/19735897/69cddeb8-9b7b-11e6-9f66-0696cfbaec00.png)
![image](https://cloud.githubusercontent.com/assets/283343/19735919/7cae484c-9b7b-11e6-850c-669e997fcf88.png)
![image](https://cloud.githubusercontent.com/assets/283343/19736043/04d944ba-9b7c-11e6-9006-283820c3fe65.png)

Full (strict) instead of "Full" does not work because Github does not have a valid certificate.

I followed the instructions at https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/ to add a "Page Rule" so that people using HTTP are forwarded to HTTPS so they can always use the "locate me" API.

**Comment by carpeliam** [comment]
Looks good to me! Thanks so much to @thadk @WheresHJ and @beechnut for getting this knocked out. 🤘
