### ISSUE TITLE
display polling location list items into an accordion

### ISSUE THREAD

**Issue by osesina** [codeforboston/cambridge_voting_locations#53]
(minimize all hours and address information into an accordion)

**Comment by osesina** [comment]
I have the address and hours listed as:
=========================
0
125 Sixth St, Cambridge, MA
Tue, Oct 24th 2:00pm to Oct 24th 8:00pm
Wed, Oct 25th 9:00am to Oct 25th 5:00pm
Thu, Oct 26th 2:00pm to Oct 26th 8:00pm
Fri, Oct 27th 9:00am to Oct 27th 5:00pm
Sat, Oct 28th 9:00am to Oct 28th 5:00pm
Sun, Oct 29th 9:00am to Oct 29th 5:00pm
Tue, Oct 31st 2:00pm to Oct 31st 8:00pm
Wed, Nov 1st 9:00am to Nov 1st 5:00pm
Thu, Nov 2nd 2:00pm to Nov 2nd 8:00pm
Fri, Nov 3rd 9:00am to Nov 3rd 5:00pm
Sat, Nov 4th 9:00am to Nov 4th 5:00pm
============================
Currently working on css file for formatting

**Comment by osesina** [comment]
Added location name to address and a little formatting, now we have:
======================================
1
Robert W. Healy Public Safety Facility
125 Sixth St, Cambridge, MA
Tue, Oct 14:00 to 20:00
Wed, Oct 9:00 to 17:00
Thu, Oct 14:00 to 20:00
Fri, Oct 9:00 to 17:00
Sat, Oct 9:00 to 17:00
Sun, Oct 9:00 to 17:00
Tue, Oct 14:00 to 20:00
Wed, Nov 9:00 to 17:00
Thu, Nov 14:00 to 20:00
Fri, Nov 9:00 to 17:00
Sat, Nov 9:00 to 17:00
...
=========================

**Comment by carpeliam** [comment]
fixed by #65.
