### ISSUE TITLE
Missing font on votecambridge.com

### ISSUE THREAD

**Issue by lucyq** [codeforboston/cambridge_voting_locations#76]
I'm getting the following console error on votecambridge.com

"Mixed Content: The page at 'https://votecambridge.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,600italic,700,800|Rokkitt:400,700'. This request has been blocked; the content must be served over HTTPS."

The font for the headings isn't loading

**Comment by lucyq** [comment]
Could we just download the fonts and point to them locally to avoid this?

**Comment by thadk** [comment]
I think we just need to change the URL of the fonts in our HTML to have an "S" in http -> https.
There is a setting I can turn on in the HTTPS service which will make this change for us  transparently/magically, but that might be confusing later.

**Comment by thecristen** [comment]
I'd go with what @thadk said.
If somehow that doesn't work, I found the font files...
https://github.com/google/fonts/tree/master/ofl/rokkitt (SIL Open Font License)
https://github.com/google/fonts/tree/master/apache/opensans (Apache license)

**Comment by carpeliam** [comment]
Yep, what @thadk said. The current wisdom is to always use https when available (replacing the old wisdom, which was to use whatever the same protocol you were already on). I believe google fonts support this.
